# Generated by Django 4.2.6 on 2023-11-13 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateField(default=datetime.date(2003, 12, 1)),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=datetime.date(2003, 12, 1)),
        ),
    ]
