# Generated by Django 4.2.6 on 2023-12-27 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_total_votes_question_total_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpeg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 12, 27)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 12, 27)),
        ),
    ]
